class DoData {
  ///
}

List<Map<String, dynamic>> generateData({int n = 10}) {
  return _data;
}

const _data = [
    {
      "id": 213,
      "name": "Cкважина",
      "well": "1512",
      "pad": "12",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 214,
      "name": "Cкважина",
      "well": "1557",
      "pad": "22А",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 215,
      "name": "Cкважина",
      "well": "3100",
      "pad": "251Б",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 216,
      "name": "Cкважина",
      "well": "3101",
      "pad": "263Б",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 217,
      "name": "Cкважина",
      "well": "3133",
      "pad": "250",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 218,
      "name": "Cкважина",
      "well": "4141",
      "pad": "266",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 261,
      "name": "Cкважина",
      "well": "1406г",
      "pad": "11",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 262,
      "name": "Cкважина",
      "well": "1426",
      "pad": "11",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 263,
      "name": "Cкважина",
      "well": "1716",
      "pad": "33",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 264,
      "name": "Cкважина",
      "well": "266ПО",
      "pad": "251Б",
      "prep_object": "ДНС-2 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 302,
      "name": "Cкважина",
      "well": "1721",
      "pad": "178",
      "prep_object": "ДНС-1 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 303,
      "name": "Cкважина",
      "well": "1722",
      "pad": "178",
      "prep_object": "ДНС-1 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 304,
      "name": "Cкважина",
      "well": "1816",
      "pad": "17",
      "prep_object": "ДНС-1 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 305,
      "name": "Cкважина",
      "well": "2020",
      "pad": "1Б",
      "prep_object": "ДНС-1 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 306,
      "name": "Cкважина",
      "well": "2062",
      "pad": "17",
      "prep_object": "ДНС-1 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
    {
      "id": 307,
      "name": "Cкважина",
      "well": "2063",
      "pad": "17",
      "prep_object": "ДНС-1 Еты-Пуровского",
      "field": "Еты-Пуровское",
      "company": "ГПН-ННГ",
      "activity": "",
      "comment": "",
      "date_planning": "",
      "date_fact": "",
      "date_creation": "01.04.2023",
      "responsible_person": "",
      "obj_status": "",
      "failure": "",
    },
  ];